# ----------------------------------------------------------------------
# | Base Settings                                                      |
# ----------------------------------------------------------------------

# Set prefix to Ctrl+Space
unbind C-a
set -g prefix C-Space
bind C-Space send-prefix

# Reload Config Keybind

## Unbind the default binding for r (which is usually 'refresh-client')
unbind r

## Bind r to reload the tmux config file
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Set Mouse
set-option -g mouse on

# Extensive History
set-option -g history-limit 100000

# Window & Pane Numbering

## Start window numbering from 1
set-option -g base-index 1

## Renumber windows when one is closed
set-option -g renumber-windows on

## Start pane numbering from 1
set-option -g pane-base-index 1

## Create new window after the current one
bind c new-window -a

# Set pane title

# Active pane app is the title we display
set-option -g set-titles on
set-option -g set-titles-string "#{pane_title}"

# Split From Current Path

## Vertical
bind '"' split-window -c "#{pane_current_path}"

## Horizontal
bind % split-window -h -c "#{pane_current_path}"

# Server Options
set-option -s focus-events on
set-option -s extended-keys on
set-option -s escape-time 0

# ----------------------------------------------------------------------
# | Status bar                                                         |
# ----------------------------------------------------------------------

RED="#AF5F5F"
GREEN="#5F875F"
YELLOW="#FF8700"
BLUE="#5F87AF"
MAGENTA="#5F5F87"
CYAN="#5F8787"
BLACK="#1C1C1C"
DARK_GRAY="#262626"
LIGHT_GRAY="#6C6C6C"
#BG="#87875F"
BG="#5F8787"
FG="#1C1C1C"

# Notified when something happens in one of the other windows
setw -g monitor-activity on
set -g visual-activity on

# Periodically refresh the status bar
set -g status-interval 60

# Basic colors of the Statusbar
set-option -g status-style bg=${BG},fg=${FG}

# Customize what is displayed
set -g status-justify left
set -g status-left-length 50
set -g status-left " #S / "
#                     └─ current session name
set -g status-right " %R "
#                     └─ current time


# Set True Color
#set-option -sa terminal-overrides ",xterm*:Tc"
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "screen-256color"



