# Kitty Configuration

# Shell
# shell /opt/homebrew/bin/tmux

# Font
font_family      Hack Nerd Font
font_size        12.0

# Background Opacity
background_opacity 0.65
dynamic_background_opacity yes

# Selection
copy_on_select yes
strip_trailing_spaces smart

# Theme (Apprentice-like colors can be added here)
