# Kitty Configuration

# Shell
# shell /opt/homebrew/bin/tmux

# Font
font_family      Hack
font_size        14.0

# Scrollback
scrollback_lines 100000

# Window
hide_window_decorations titlebar-only
macos_titlebar_color background
confirm_os_window_close 0
window_padding_width 10

# Tab Bar
tab_bar_edge top
tab_bar_style separator
tab_separator ""
tab_bar_margin_height 5.0 5.0
tab_title_template "{fmt.fg.#7f7f7f}┇{fmt.fg.default} {title} "
active_tab_foreground   #1c1c1c
active_tab_background   #709772
active_tab_font_style   bold
inactive_tab_foreground #7f7f7f
inactive_tab_background #1c1c1c
inactive_tab_font_style normal
tab_bar_background      #1c1c1c

# Background Opacity
background_opacity 0.75
dynamic_background_opacity yes

# Selection
copy_on_select yes
strip_trailing_spaces smart

# URLs
url_color #7199bc
url_style curly
open_url_with default
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh
detect_urls yes
show_hyperlink_targets yes
underline_hyperlinks hover
url_excluded_characters )]

# Theme
include dark-theme.auto.conf
